{% set name = "ipywidgets" %}
{% set version = "7.6.4" %}
{% set sha256 = "028bf014a0b1d77cb676fe163115f145aacdde0bb9a51c4166940e5b62a7d1d0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ipykernel >=4.5.1
    - nbformat >=4.2.0
    - traitlets >=4.3.1
    - widgetsnbextension

test:
  imports:
    - ipywidgets
    - ipywidgets.widgets

about:
  home: http://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: IPython HTML widgets for Jupyter
  doc_url: https://ipywidgets.readthedocs.io/
  dev_url: https://github.com/jupyter-widgets/ipywidgets/releases/tag/7.2.1
